import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/contexts/users/userContext";
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <NuqsAdapter>
                    <UserProvider>
                        {children}
                    </UserProvider>
                </NuqsAdapter>
            </body>
        </html>
    );
}
